### ISSUE TITLE
Error not surfaced properly

### ISSUE THREAD

**Issue by equalsJeffH** [tobie/pr-preview#119]
See w3c/webauthn#1663.  The error message claims that the CSS spec preprocessor failed.

However, I just now built the spec "by hand" successfully using https://api.csswg.org/bikeshed/.  It does issue some warnings and link errors, but that has been the case for months, and pr-preview has been fine with that.  

Also I apparently just now built the spec at the latest commit using this URL that pr-preview's error message (on w3c/webauthn#1663) provided: 
https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fwebauthn%2F17f3aa2fb46ac36be5fbb185f02a98ea1952ec01%2Findex.bs&force=1&md-warning=not%20ready

(i.e., it rendered fine in my browser window)

(also, I'm building it fine locally (with the non-fatal warnings and link errors))

cc: @tabatkins

**Comment by tabatkins** [comment]
It looks like it was a temporary hiccup - the PR Preview seems fine now.

(The server has been hit by some high-volume crawlers lately that have been making it unstable.)

**Comment by equalsJeffH** [comment]
yes, pr-preview auto re-built the spec successfully, thanks for checking !
