### ISSUE TITLE
Error not surfaced properly

### ISSUE THREAD

**Issue by gkellogg** [tobie/pr-preview#137]
See w3c/rdf-n-quads#4.

I've been getting preview errors ever since we attempted to use a submodule for part of the repo. That change has been reverted, and the raw file builds properly using spec-generator. Can't figure out what's going on with this, and other repositories:

Related URL: https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Frdf-n-quads%2F42ac2c94320e303a32159fb31bc6084c865824a2%2Fspec%2Findex.html%3FisPreview%3Dtrue

I previously had the same error on w3c/rdf-concepts#10.

> 😭  Sorry, there was an error generating the HTML. Please report this issue!
Specification: http://labs.w3.org/spec-generator/uploads/3qRgOi/spec/index.html?isPreview=true%3FisPreview%3Dtrue&publishDate=2023-02-01
ReSpec version: 32.7.0
File a bug: https://github.com/w3c/respec/
Error: Error: Evaluation failed: Timeout: document.respec.ready didn't resolve in 28690ms.
    at ExecutionContext._ExecutionContext_evaluate (/u/spec-generator/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/u/spec-generator/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async generateHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:221:12)
    at async toHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:92:18)
    at async Object.generate [as respec] (file:///u/spec-generator/generators/respec.js:15:44)
    at async file:///u/spec-generator/server.js:252:48

cc/ @pchampin

**Comment by gkellogg** [comment]
Actually, the problem could be because the version it's compared to used submodules, and that is somehow failing. Although corrected in this PR, the diff can't be built. If that's so, then doing another PR to w3c/rdf-concepts, where the issue also occurred, but where that PR was pulled, would be telling.

**Comment by tobie** [comment]
Your later comment sounds like a reasonable explanation.

**Comment by gkellogg** [comment]
So, I created w3c/rdf-concepts#12 on top of the previously merged w3c/rdf-concepts#10, and it continues to fail, so that may not be the problem after all.

**Comment by gkellogg** [comment]
Now seeing the problem in w3c/rdf-canon#79, where there haven't been issues before. Changes from "main" branch are pretty innocuous.

**Comment by tobie** [comment]
Now seems to be fixed?

**Comment by gkellogg** [comment]
Yes, seems to be working now.
