### ISSUE TITLE
Error not surfaced properly

### ISSUE THREAD

**Issue by shhnjk** [tobie/pr-preview#147]
See whatwg/html#9309.

**Comment by tobie** [comment]
Seems Wattsi server has an issue with your markup. Nothing I can help with from here, unfortunately. Closing.

**Comment by shhnjk** [comment]
@tobie, running [this](https://github.com/whatwg/build.whatwg.org#readme) successfully build. So I'm not sure what's happening. How do I request PR Preview to re-try building?

**Comment by tobie** [comment]
@shhnjk push a new commit or just edit the pull request text on GitHub itself (e.g. add a line break).

**Comment by tobie** [comment]
Also, make sure you `git fetch main` before rebasing.

**Comment by shhnjk** [comment]
> @shhnjk push a new commit or just edit the pull request text on GitHub itself (e.g. add a line break).

Thanks! This one worked!
