### ISSUE TITLE
Error not surfaced properly

### ISSUE THREAD

**Issue by TallTed** [tobie/pr-preview#149]
See w3c/vc-data-model#1429.

**Comment by tobie** [comment]
Should now be fixed. You'll have to slightly edit the PR's body to kickstart a new build.

**Comment by tobie** [comment]
Reopening as the fix I landed doesn't work.

Closing again as a duplicate of #148.

**Comment by tobie** [comment]
Indeed, @TallTed, apologies for the mix-up. What were the odds of two entirely different issues with very similar profiles happening the very same weekend I was at FOSDEM!? Bigger than 0, apparently!
