### ISSUE TITLE
pr-preview bot doesn't seem to be working

### ISSUE THREAD

**Issue by mgiuca** [tobie/pr-preview#15]
I created this PR this morning: w3c/manifest#647

Several hours later, the Preview and Diff buttons still haven't shown up, nor has the page been created on pr-preview.s3.amazonaws.com (expecting to see something at https://pr-preview.s3.amazonaws.com/mgiuca/manifest/pull/647.html).

Has something broken? This worked yesterday.

**Comment by mgiuca** [comment]
It worked again when I pushed a new commit. Maybe was down for a bit.

**Comment by tobie** [comment]
That’s weird. Just editing the content of the pull request body using the web interface (eg adding a line break) triggers a build. Easier than force pushing.

**Comment by mgiuca** [comment]
Thanks, that's good to know.

**Comment by mgiuca** [comment]
Hmm, I uploaded a new patch set today. No PR Preview. Then I force-uploaded a new version of a commit (just changed the date stamp; did not create a new commit). Then I edited the pull request body, as you suggested above.

Still no PR Preview (has been about an hour). Maybe something is stuck?

**Comment by tobie** [comment]
Sorry, missed this until today.

Is the issue fixed, now?

**Comment by tobie** [comment]
Oh this has been merged in the meantime, I see.

OK, if this shows up again, please reopen this issue.
