### ISSUE TITLE
Error: 429 Too Many Requests from HTML Diff Service

### ISSUE THREAD

**Issue by jyasskin** [tobie/pr-preview#153]
See w3ctag/privacy-principles#419 and https://github.com/w3ctag/privacy-principles/pull/417.

The error message includes "🔗 [Related URL]([object Object])", which is probably a bug in PR Preview itself. I'm not sure if the [HTML Diff Service](http://services.w3.org/htmldiff) rate limit is PR Preview actually sending too many requests or the Diff Service being too restrictive.

**Comment by gosko** [comment]
I disabled rate-limiting for the htmldiff service if the user-agent contains pr-preview. Sorry for the hassle!

**Comment by jyasskin** [comment]
Confirmed as fixed in https://github.com/w3ctag/privacy-principles/pull/419. Thanks!
