### ISSUE TITLE
Error not surfaced properly (HTML Diff might have changed its invocation contract)

### ISSUE THREAD

**Issue by annevk** [tobie/pr-preview#156]
See whatwg/url#846.

It seems HTML Diff changed its invocation contract? "Error: options.uri is a required argument"

**Comment by annevk** [comment]
cc @dontcallmedom

**Comment by tobie** [comment]
Sorry, I just introduced this bug minutes ago while fixing something else.

**Comment by annevk** [comment]
Thanks @tobie!
