### ISSUE TITLE
PR-Preview failing for multiple repos due to timeouts

### ISSUE THREAD

**Issue by TallTed** [tobie/pr-preview#158]
See w3c/sparql-update#46 *for one example.*

PR-Preview has not been generating properly for some days (maybe weeks?) on various repositories, with no obvious error to report — just these 30s timeouts.

**Comment by afs** [comment]
https://github.com/w3c/sparql-update/pull/46 is working.

pr-preview is very useful when editing spec documents. Thank you.

**Comment by TallTed** [comment]
The timeouts seem to have been resolved. If anyone reading this has information on their cause, or the resolution, it would be good to include that here.

**Comment by tobie** [comment]
Timeouts are usually caused by the document not being a properly formatted ReSpec document.

**Comment by TallTed** [comment]
> Timeouts are usually caused by the document not being a properly formatted ReSpec document.

Shouldn't that result in an error of some kind? A timeout is a black hole.

**Comment by tobie** [comment]
You should take it up with the relevant services. I have no control over them.

**Comment by TallTed** [comment]
> You should take it up with the relevant services. I have no control over them.

I'd be happy to. I reported here, because the alert said to do so if I couldn't decipher the error further. I like to think I'm pretty tech savvy, but I'm not enough to decipher what service is at fault, nor where nor to whom to report the issue.

**Comment by tobie** [comment]
I can’t see the error you had anymore, but I think it should have surfaced most if not all of these data points: https://github.com/tobie/pr-preview/blob/4e7fe76cbc0cfd123a07fef23cfca0983d7f88ea/lib/services.js#L8

**Comment by TallTed** [comment]
I'm sorry, I don't understand what data points are surfaced by `exports.RESPEC = {`, nor what to do with them. I'd guess we might as well table this, given that the error isn't happening now.

**Comment by tobie** [comment]
Fixed the URL so the preview didn’t obscure my point by showing only the first line of the data structure.

**Comment by tobie** [comment]
Pull request to improve the error messages here: #160
