### ISSUE TITLE
Support spec per directory

### ISSUE THREAD

**Issue by upsuper** [tobie/pr-preview#19]
The spec repo for CSSWG has a large number of specs, mostly one in a directory.

It would probably be helpful if the preview can be configured and generated at a per-directory granularity.

**Comment by tobie** [comment]
I'm happy to take a PR or consider contracting options to enable this feature.

**Comment by foolip** [comment]
Is this a dupe of https://github.com/tobie/pr-preview/issues/18?

**Comment by tobie** [comment]
Pretty much, yes.
