### ISSUE TITLE
Handle the case where the same branch name is used for multiple PRs

### ISSUE THREAD

**Issue by foolip** [tobie/pr-preview#2]
See https://github.com/whatwg/meta/issues/16#issuecomment-281291621 and following comments.

**Comment by tobie** [comment]
Fixed for everything but WHAT WG specs in https://github.com/tobie/pr-preview/commit/79441ae63f7fa34d9e34b944a6c92feef72c757f.

**Comment by foolip** [comment]
Can this be seen in action somewhere yet? Maybe we should copy the same naming convention :)

**Comment by tobie** [comment]
This is already deployed. WHAT WG is opting out of it to keep things on its own domain. My plan to solve this is to have a dedicated S3 bucket for WHAT WG with a subdomain of whatwg.org pointing to it.

**Comment by foolip** [comment]
Wait, so the plan is to actually use the code in this repo for WHATWG as well, as opposed to us tweaking https://github.com/whatwg/whatwg.org/tree/master/resources.whatwg.org/build? @domenic?

**Comment by foolip** [comment]
Oh, right, there's the bit about actually updating the PR comment to link to it, of course.

**Comment by tobie** [comment]
PR-preview needs to build everything on its side anyway, if only to make and display the diffs. Linking to the WHAT WG files is a [minor cosmetic change](https://github.com/tobie/pr-preview/blob/0efab730c06689edcf4594d13971b8252cd51418/lib/views/body.js#L79-L84) that's added to the comments.

I'm now working on adding preview for HTML, and I'll either need to use a dedicated S3 bucket, or have an easy solution to upload a bunch of files to WHATWG servers.

**Comment by tobie** [comment]
I think this is no longer an issue? Feel free to re-open otherwise.
