### ISSUE TITLE
pr-preview not running on web-share-target repo

### ISSUE THREAD

**Issue by mgiuca** [tobie/pr-preview#20]
Hi Tobie, (+cc @ewilligers)

We've noticed that pr-preview hasn't run for the past few PRs put into the web-share-target repo:

- WICG/web-share-target#44
- WICG/web-share-target#46
- WICG/web-share-target#48
- WICG/web-share-target#49
- WICG/web-share-target#50
- WICG/web-share-target#52
- WICG/web-share-target#53

(The earliest one being on July 19, 2018). Previously it was automatically running.

Is something broken on the server side? Not sure if this is specific to the web-share-target repo or more global.

Thanks.

**Comment by tobie** [comment]
It seems to be working elsewhere, so this is probably a repo specific issue.

**Comment by mgiuca** [comment]
@tobie Can you think of any reason why it would suddenly stop working for a particular repo?

The [.pr-preview.json](https://github.com/WICG/web-share-target/blob/master/.pr-preview.json) has not changed since it was added in October 2017.

**Comment by tobie** [comment]
@mgiuca what changed in the spec? A common problem is this: https://github.com/tobie/pr-preview#known-issues

Alternatively, are there other Respec specs having issues?

**Comment by mgiuca** [comment]
Hmm, well we aren't using "async" but we also weren't using "defer". I've added "defer":
https://github.com/WICG/web-share-target/commit/4df748ae4eb07046d4f01508e117e6bef5552323

We'll see if that helps.

@marcosc Have you heard of any other Respec repos having this issue?

**Comment by mgiuca** [comment]
@marcoscaceres ^^ (since I didn't at you properly before)

**Comment by marcoscaceres** [comment]
Not that I know of. All my specs are seem to be ok?

**Comment by marcoscaceres** [comment]
@mgiuca checking if the spec generator is ok... will report back.

**Comment by marcoscaceres** [comment]
@mgiuca tested it here with a fresh PR on Manifest:
https://github.com/w3c/manifest/pull/709

And it generates correctly: 
https://pr-preview.s3.amazonaws.com/w3c/manifest/709/60a5156...37eaa77.html#usage-examplesdfasasfdasadsf

**Comment by marcoscaceres** [comment]
maybe it's something to do with the WICG org settings... having a look.

**Comment by marcoscaceres** [comment]
Yeah, that was it... try it now :)

**Comment by tobie** [comment]
@mgiuca, can you just comment in the body of the PR (just edit the content via the web interface). That should trigger a new build.

**Comment by mgiuca** [comment]
Thanks, it seems to be working.

It did take 20 hours for it to show up, but I suspect it's aligned with Marcos's comment on WICG/web-share-target#64, which triggered the bot. So future PRs should work.

Thanks @tobie and @marcoscaceres !

**Comment by marcoscaceres** [comment]
@mgiuca, for any outstanding issues, just close the PR and reopen it... that causes the script to run.

**Comment by mgiuca** [comment]
Several new PRs Eric put up are not working:

- WICG/web-share-target#65
- WICG/web-share-target#66

And some older ones that I commented on did not get updated with pr-preview:

- WICG/web-share-target#62
- WICG/web-share-target#63

@marcoscaceres Why do you think your comment on WICG/web-share-target#64 worked, but these others didn't.

**Comment by marcoscaceres** [comment]
Is all good. Thanks for helping confirm it's working ok. We got there in the end :)
