### ISSUE TITLE
We broke PR preview for HTML; please help us

### ISSUE THREAD

**Issue by domenic** [tobie/pr-preview#24]
In particular the web service needs a new file for MDN data. See https://github.com/whatwg/html-build/commit/c29870d9d9fc8c9edc054ad34f6306cc6433c226 for details. The TLDR is:

- Download https://raw.githubusercontent.com/w3c/mdn-spec-links/master/html.json
- Pass it as a file under the name `mdn` to the wattsi server.

Hopefully we'll put together a full html-build server soon (TM) so that this doesn't happen again...

**Comment by sideshowbarker** [comment]
I’m happy to help as needed with making this work

**Comment by tobie** [comment]
Just completely accidentally saw this now. You should have emailed me. Sorry about missing this. Is the issue fixed, now?
