### ISSUE TITLE
Support vanilla html previews

### ISSUE THREAD

**Issue by nigelmegitt** [tobie/pr-preview#28]
The docs say at the moment the only two values of `"type"` supported in the `.pr-preview.json` config file are `respec` and `bikeshed`. I tried switching PR Preview on for the https://github.com/w3c/charter-timed-text repo and realised when it didn't work that the file in there is a plain vanilla html file that doesn't need either bikeshed or respec processing to generate the output.

So this is a feature request to support vanilla html file previews too.

**Comment by tobie** [comment]
Oh, interesting. I could certainly implement that. No ETA, but also happy to consider a PR.

**Comment by nigelmegitt** [comment]
Sorry, I just noticed this, thank you!
