### ISSUE TITLE
Error not surfaced properly

### ISSUE THREAD

**Issue by annevk** [tobie/pr-preview#30]
I suspect PR Preview is failing all over because W3C Bugzilla is down and no longer maintained.

See whatwg/html#4465.

**Comment by annevk** [comment]
cc @domenic

**Comment by tobie** [comment]
Sorry, just saw this now. What's the plan with that now broken W3C Bugzilla link?

**Comment by domenic** [comment]
Wattsi hasn't taken the Bugzilla CSV file for a while, so it's not necessary. See e.g. https://github.com/whatwg/html-build/blob/4573bf72f482098ae8c36542ea66adf6a0979fe4/build.sh#L570 for an invocation.
