### ISSUE TITLE
pr-preview seems broken for respec documents

### ISSUE THREAD

**Issue by deniak** [tobie/pr-preview#31]
PR preview no longer provides snapshots for respec based documents, e.g.:
* https://github.com/w3c/wpub/pull/427
* https://github.com/w3c/json-ld-syntax/pull/162
* https://github.com/w3c/json-ld-framing/pull/48

It used to work ~3 weeks ago.
spec-generator still generates the snapshots as expected. Can you provide the logs to help debug the issue?

**Comment by tobie** [comment]
This should now be fixed.

**Comment by deniak** [comment]
thanks @tobie
