### ISSUE TITLE
Disappearing links do not show up in the HTML diff

### ISSUE THREAD

**Issue by annevk** [tobie/pr-preview#5]
I suspect this can only be fixed upstream (happy to file, where?), but this seems like a good place to collect such issues.

**Comment by annevk** [comment]
(There might be other ways of solving this through better Bikeshed / Shepherd tooling.)

**Comment by tobie** [comment]
Sorry, I somehow just saw this now. o_O

This seems like an issue with the HTML differ itself, though I might be wrong. Would you have an example to point to?

**Comment by annevk** [comment]
I don't recall. I suspect it was something like `<a href=...>term</a>` becoming `term` due to Bikeshed no longer finding what was referenced and that not showing up as a change.

**Comment by tobie** [comment]
Isn't that something the CLI tool picks up? (Sorry, a little rusty after a long break).

**Comment by annevk** [comment]
Yeah, I think it mostly does these days. I'll reopen this if I encounter it again.
