### ISSUE TITLE
pr preview bot not updating

### ISSUE THREAD

**Issue by sidvishnoi** [tobie/pr-preview#50]
PR: https://github.com/w3c/wot-thing-description/pull/872

There are multiple cases of preview not updating. Here's what I did:
- Pushed 3 commits, one at a time. Only first 2 updated PR description with comment (can be seen in description comment's edit history).
- Then did a rebase to master and squash (force push), PR preview didn't update the diff.
- Then closed and reopened the PR, just to see if PR preview updates. PR preview still didn't update the diff.

**Comment by tobie** [comment]
Sorry I missed this. Was it resolved for you?

**Comment by sidvishnoi** [comment]
Nope. Will re-open if I face this again.
