### ISSUE TITLE
HTML Diff Service Error

### ISSUE THREAD

**Issue by npm1** [tobie/pr-preview#51]
Is this just happening in Paint Timing (and hence I should be looking into it) or is this more widespread? See w3c/paint-timing#66 for an example.

**Comment by domenic** [comment]
Happening in HTML too. https://github.com/whatwg/html/pull/5351 for example.

However interestingly the "related URL" takes me to a diff I can view in my browser, so it's not clear if the problem is on the HTML Diff Viewer's side or PR Preview's...

**Comment by andreubotella** [comment]
Same here in Encoding (whatwg/encoding#203).

**Comment by tobie** [comment]
@dontcallmedom I'm getting the following errors when curling into services.w3.org: 

```
$ curl -I "https://services.w3.org/"        
curl: (35) error:1400442E:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert protocol version
```
I'm getting a similar issue from Heroku despite having updated the stack.

@ylafon is this related to the TSL update you've pinged me about?

**Comment by tobie** [comment]
So my hunch is that this is related to W3C having updated to TLS 1.3 recently and Heroku [not supporting it](https://devcenter.heroku.com/articles/ssl#ssl-details).

I'm out of my depth, here, and also have limited bandwidth to tackle this issue.

I could ask Heroku to enable TLS 1.3 for PR Preview, though I'm unsure they would do it. I'm also unclear as to what this would imply for the other services PR Preview relies on.

Suggestions as to how to move forward with this are welcomed.

**Comment by dontcallmedom** [comment]
looking if we can revert the change while a better solution gets figured out, will keep you posted

**Comment by ylafon** [comment]
@tobie services.w3.org is allowing tls1.2 and tls1.3, but it seems that the server was in a weird state. restarted now, did that fix your issue?

**Comment by domenic** [comment]
Let's find out; I'll try to re-trigger one of the PR preview builds...

**Comment by tobie** [comment]
Seems fixed. :) Thanks all! <3

**Comment by domenic** [comment]
Fixed! https://github.com/whatwg/encoding/pull/203 and https://github.com/whatwg/html/pull/5360 now have the preview.

For anyone else: you need to edit your post (e.g. add whitespace) and the build will re-trigger.
