### ISSUE TITLE
WHATWG sets a warning in our default Bikeshed boilerplate, which PR Preview overrides

### ISSUE THREAD

**Issue by domenic** [tobie/pr-preview#55]
In https://github.com/tabatkins/bikeshed/blob/master/bikeshed/boilerplate/whatwg/computed-metadata-LS-PR.include we have set the `warning` metadata to `custom` for all WHATWG spec builds with the LS-PR status. This makes it use the warning at https://github.com/tabatkins/bikeshed/blob/master/bikeshed/boilerplate/whatwg/warning-custom.include.

However, when deploying using PR Preview, this gets overridden. See, for example, https://whatpr.org/storage/86.html. This is due to https://github.com/tobie/pr-preview/blob/a38138ef02f65d8829a2c01c5a7195fa7b4ea941/lib/models/config.js#L44-L47.

I'm unsure of the best solution for working around this conflict. There's no way to know precisely that the default metadata for a given org/status has set `md-warning`, so I understand why you're relying on the incoming config instead.

Maybe we could hard-code an exception for `LS-PR` statuses, on the reasoning that they probably have their own custom warning anyway by virtue of being a special status dedicated for PR previews?

**Comment by annevk** [comment]
@tobie what do you think? See also #56. (Pinging you as you do not seem to be watching this repository.)

**Comment by tobie** [comment]
Thanks for flagging this, there was indeed something fishy going on with notifications.
