### ISSUE TITLE
Include additional files such as json

### ISSUE THREAD

**Issue by OR13** [tobie/pr-preview#80]
I would like to render some test results in respec that are pulled from a seperate json file.

is it possible for PR preview to copy json files, such that the can be fetched using relative / absolute paths?

**Comment by tobie** [comment]
Not at present, unfortunately.

**Comment by OR13** [comment]
@tobie thanks! I ended up scripting json injection into script tags using `cheerio`, the build process now just replaced those script tags with the latest json.... its probably better solution that splitting up the files from a "all things in one place perspective".
