### ISSUE TITLE
PR Preview is not retrying

### ISSUE THREAD

**Issue by annevk** [tobie/pr-preview#81]
It seems https://github.com/whatwg/html/pull/5909 is not being tried again despite being modified recently (both the comment and the branch).

**Comment by tobie** [comment]
I'm assuming this ended-up being fixed or being a one off issue? Please feel free to reopen otherwise.

**Comment by annevk** [comment]
I'm not sure, but will let you know if it continues to happen. We switched some tooling around (moved to GitHub Actions and even more Docker I believe) so maybe there were some side effects.
