### ISSUE TITLE
PR Preview is not retrying

### ISSUE THREAD

**Issue by annevk** [tobie/pr-preview#82]
I continue to see #81, latest at https://github.com/heycam/webidl/pull/929. Yesterday I tried to get https://github.com/whatwg/html/pull/5953 updated and that didn't work.

**Comment by tobie** [comment]
I don't have any trace in the logs of whatwg/html#5953 and don't have permission to restart it myself. I was able to restart heycam/webidl#929, and that worked.

Could you restart whatwg/html#5953 and LMK when you did?

**Comment by annevk** [comment]
I'm afraid I don't follow. Restart the CI build or do a force push or what?

**Comment by tobie** [comment]
> I'm afraid I don't follow. Restart the CI build or do a force push or what?

Just edit the body of the pull request. Adding a couple line breaks is enough.

**Comment by annevk** [comment]
I did that yesterday and did it again just now. Crickets so far.

In the IDL case though, why didn't the subsequent commit retrigger things?

**Comment by tobie** [comment]
So as mentioned on irc, this is triggering an error ("Error: request entity too large") at the level of the Express framework itself. Need to investigate what exactly is happening and why.
