### ISSUE TITLE
Get "Access Denied Error" on link pages from main `html` src

### ISSUE THREAD

**Issue by rmeritz** [tobie/pr-preview#83]
The "Preview" and "Diff" link works correctly, but all pages linked to getting AWS access denied errors.

If I look at the html page locally all the links work. 

The links are relative links to other html pages in the repo.

Here is an example of PR where the problem exists: https://github.com/w3c/aria-at/pull/307
Here is the working main index: https://pr-preview.s3.amazonaws.com/w3c/aria-at/pull/307.html
Here is an example of a link from that page with an access denied error: https://pr-preview.s3.amazonaws.com/w3c/aria-at/pull/tests/combobox-autocomplete-both/index.html

Is there a way to specify those links in the `href` so they work as well? 

My idea for a work around is to link directly to `rawgit` myself, but that seems unideal.

**Comment by tobie** [comment]
Unfortunately, PR Preview is really designed to build a single page-spec per repo, with the exception of the HTML spec, which has a dedicated code path.

There are plans to support multiple specs per repo (CSS WG-style), but I don't think that would help with your use case.

I don't know that supporting your use case would be simple given the app's architecture, but if it were, you were willing to implement it, and it didn't unreasonably increase the complexity of the app or its maintenance cost, I'd be happy to include it.

**Comment by rmeritz** [comment]
@tobie - Thanks for the quick response and explanation. I've decided that pr-previewer doesn't really fit our use case welll enough and going to use a custom github action instead.

**Comment by tobie** [comment]
Yeah, that seems like a more reasonable path.
