### ISSUE TITLE
Error not surfaced properly

### ISSUE THREAD

**Issue by clehner** [tobie/pr-preview#85]
See w3c/did-test-suite#34.

**Comment by tobie** [comment]
Seems like an issue with the web service tasked to build respec files. It’s probably temporary. Have you tried again? You can force a rerun by editing the content of the pull request (not the actual code, just the content on the GitHub side. Just adding a line break is enough.

**Comment by clehner** [comment]
Hi @tobie, thanks for the instructions. I edited the PR text just now. It appears that PR Preview ran again, but it gets the same error.

**Comment by tobie** [comment]
@deniak any idea what’s going on here?

**Comment by deniak** [comment]
This is an error coming from respec. @sidvishnoi, spec-generator is producing the following error while trying to process https://rawcdn.githack.com/spruceid/did-test-suite/7925112b59a2f92ee820d0afe03034e9f05af3c9/index.html?isPreview=true&publishDate=2021-03-09
```
{
    "error": "\n😭  Sorry, there was an error generating the HTML. Please report this issue!\nSpecification: https://rawcdn.githack.com/spruceid/did-test-suite/7925112b59a2f92ee820d0afe03034e9f05af3c9/index.html?isPreview=true&publishDate=2021-03-09\nReSpec version: 26.2.0\nFile a bug: https://github.com/w3c/respec/\nError: Error: Evaluation failed: TypeError: Cannot destructure property 'rsDocToDataURL' of '(intermediate value)' as it is undefined.\n    at evaluateHTML (__puppeteer_evaluation_script__:23:13)\n    at ExecutionContext._evaluateInternal (/u/spec-generator/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async ExecutionContext.evaluate (/u/spec-generator/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async generateHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:207:12)\n    at async toHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:86:18)\n    at async Object.generate [as respec] (/u/spec-generator/generators/respec.js:13:40)\n    at async /u/spec-generator/server.js:89:44\n"
}
```
Do you know if it's a bug in respec or a misconfiguration?

**Comment by tobie** [comment]
Thanks folks. Closing.
