### ISSUE TITLE
pr-preview is giving a 500 error

### ISSUE THREAD

**Issue by wanderview** [tobie/pr-preview#93]
See WICG/urlpattern#66.

The error message is:

```
Error running preprocessor, returned code: 1.
Traceback (most recent call last):
  File "/sites/api.csswg.org/bikeshed/bikeshed.py", line 6, in 
    cli.main()
  File "/sites/api.csswg.org/bikeshed/bikeshed/cli.py", line 466, in main
    handleSpec(options, extras)
  File "/sites/api.csswg.org/bikeshed/bikeshed/cli.py", line 515, in handleSpec
    lineNumbers=options.lineNumbers,
  File "/sites/api.csswg.org/bikeshed/bikeshed/Spec.py", line 61, in __init__
    self.inputSource = InputSource(inputFilename, chroot=constants.chroot)
TypeError: __init__() got an unexpected keyword argument 'chroot'
```

**Comment by tobie** [comment]
@tabatkins, this seems Bikeshwd related. Think you could help out @wanderview here?

**Comment by wanderview** [comment]
I also got the error on WICG/urlpattern#67.

**Comment by tabatkins** [comment]
Yup, caught this morning. I pushed a fix, but forgot that y'all need the pypi update to get it (I was gonna push one tomorrow, after some boilerplate updates). v3.0.1 published now, y'all should see the fix momentarily.

**Comment by tobie** [comment]
Thanks. 

@wanderview, you’ll need to edit the body of the GitHub pull request to retrigger the builder.

**Comment by wanderview** [comment]
Hmm, I'm still getting a 500.

**Comment by tabatkins** [comment]
(Fixed properly this time; I'm still a little confused about how Python works in a particular case but it's unimportant so I just hammered it into shape.)

**Comment by wanderview** [comment]
Verified.
